apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-ingress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/04Deepak/todo-gitops
    targetRevision: main
    path: applications/todo_ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
