apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: todo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-frontend-svc
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-backend-svc
                port:
                  number: 5000





# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: todo-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: todo.local
#       http:
#         paths:
#           - path: /api/?(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: todo-backend-svc
#                 port:
#                   number: 5000

#           - path: /(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: todo-frontend-svc
#                 port:
#                   number: 80
